# Generated by Django 2.2 on 2020-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200601_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dp',
            field=models.ImageField(default=None, upload_to='dp'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='fb_link',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='specialize',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
