# Generated by Django 2.2 on 2020-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200601_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='dp',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='fb_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='specialize',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
