# Generated by Django 2.2 on 2020-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200601_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='fb_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='specialize',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
