# Generated by Django 2.2 on 2020-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200601_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='followers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='following',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='dp'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='reviews',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='students',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='tw_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='views',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
